version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  movie-updates:
    docker:
      - image: cimg/python:3.12
    resource_class: small
    steps:
      - checkout
      - run:
          name: Install requirements
          command: |
            cd movie-updates
            pip install -r requirements.txt
      - run:
          name: Run the app
          command: |
            pwd
            ls -ltr
            python ~/movie-updates/movie-updates.py

workflows:
  send-updates: 
    jobs:
      - movie-updates:
        filters:
            branches:
              ignore: 
                - /.*/