apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-db
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-db
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /mnt/disks/prometheus-db
  claimRef:
    namespace: default  # Namespace where the PVC is defined
    name: prometheus-db # Name of the PVC