# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-exporter
  namespace: default
  labels:
    app: monitoring
spec:
  selector:
    matchLabels:
      app: monitoring
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: monitoring
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name: node-exporter
        image: bitnami/node-exporter:1.8.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9100
          name: node-exporter
#        volumeMounts:
#        - name: localtime
#          mountPath: /etc/localtime
#      volumes:
#        - name: localtime
#          hostPath:
#            path: /usr/share/zoneinfo/Asia/Taipei
      restartPolicy: Always
---
# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: default
spec:
  selector:
    app: monitoring
  type: NodePort
  ports:
  - name: node-exporter-port
    protocol: TCP
    port: 9100
    targetPort: 9100
    nodePort: 30003
---
