version: '3.1'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
    - 9090:9090
    volumes:
    - prometheus-data:/prometheus
    - ./prometheus-compose.yml:/etc/prometheus/prometheus.yml
    command:
    - '--web.enable-lifecycle'
    - '--config.file=/etc/prometheus/prometheus.yml'
    restart: unless-stopped

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    command:
    - '--path.rootfs=/host'
    # - '--collector.textfile.directory=/tmp'
    pid: host
    restart: unless-stopped
    volumes:
    - '/:/host:ro,rslave'
    # - '/tmp:/tmp:ro'
    

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
    - 3000:3000
    restart: unless-stopped
    environment:
    - GF_SECURITY_ADMIN_USER=vishnu
    - GF_SECURITY_ADMIN_PASSWORD=vishnu
    volumes:
    - grafana:/etc/grafana/provisioning/datasources

  pushgateway:
    image: prom/pushgateway:v1.1.0
    container_name: pushgateway
    restart: unless-stopped
    ports:
    - 9091:9091

volumes:
    prometheus-data:
    grafana: