#custom file created for deployment with the docker compose file
global:
  scrape_interval: 15s
  scrape_timeout: 10s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText0.0.4
  evaluation_interval: 15s
runtime:
  gogc: 75
alerting:
  alertmanagers:
  - follow_redirects: true
    enable_http2: true
    scheme: http
    timeout: 10s
    api_version: v2
    static_configs:
    - targets: []

scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  track_timestamps_staleness: false
  scrape_interval: 15s
  scrape_timeout: 10s
  scrape_protocols:
  - OpenMetricsText1.0.0
  - OpenMetricsText0.0.1
  - PrometheusText0.0.4
  metrics_path: /metrics
  scheme: http
  enable_compression: true
  follow_redirects: true
  enable_http2: true
  static_configs:
  - targets:
    - localhost:9090

- job_name: node_exporter
  scrape_interval: 15s
  scrape_timeout: 10s
  relabel_configs:
  - action: replace
    source_labels: [__scheme__]
    regex: (.*)
    target_label: TLS
    replacement: $1
  static_configs:
  - targets:
    - node_exporter:9100

- job_name: push_gateway
  honor_labels: True
  static_configs:
  - targets:
    - pushgateway:9091