groups:
  - name: pod_count_rules
    rules:
      # Recording Rule to count running pods
      - record: num_running_pods
        expr: sum(kube_pod_status_phase{phase="Running"})

  - name: pod_count_alerts
    rules:
      # Alert Rule to trigger if running pods > 10
      - alert: HighNumberOfRunningPods
        expr: num_running_pods > 10
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High number of running pods"
          description: "There are more than 10 running pods in the cluster (currently {{ $value }} pods)."
