apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-app
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-app
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /mnt/disks/wordpress-app
  claimRef:
    namespace: default  # Namespace where the PVC is defined
    name: wordpress-app # Name of the PVC
---